theme: jekyll-theme-midnight
title: Ravinder Olivier Singh Dadiala
email: ravinder-Olivier@outlook.com
description: Info and projects by @ravinder-Olivier
baseurl: "/" # the subpath of your site, e.g. /blog
url: "https://ravinder-Olivier.github.io" # the base hostname & protocol for site, e.g. http://example.com
github_username:  ravinder-Olivier
